
title: Carlmont Robotics
description: Carlmont High School Robotics, Deep Blue, FRC Team 199
markdown: kramdown
highlighter: rouge

include: ["admin/config.yml"]

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
