---
---
{% if site.github.environment == "development" %}
{% comment %}For local development{% endcomment %}
# See https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
# for doing development locally.
backend:
  name: git-gateway
local_backend: true
{% else %}
backend:
  name: github
  repo: {{site.github.owner_name}}/{{site.github.project_title}} # DeepBlueRoboticsMentors/DeepBlueRoboticsMentors.github.io
  branch: master
  {% if site.github.owner_name == "DeepBlueRoboticsMentors" %}
  site_domain: flamboyant-brattain-ce0789.netlify.com
  {% elsif site.github.owner_name == "DeepBlueRobotics" %}
  site_domain: hopeful-roentgen-7d9a3b.netlify.com
  {% comment %}Add additional elsif clauses for other GitHub users/orgs Netlify site domains above this line{% endcomment %}
  {% endif %}
{% endif %}

media_folder: "images"
reusable_fields:
  - &title {label: Title, name: title, widget: string}
  - &subtitle {label: Subtitle, name: subtitle, widget: string}
  - &short_name {label: "Name in navigation bar", name: short_name, widget: string}
  - &image {label: "Image", name: image, widget: image }
  - &content {label: "Content", name: content, widget: markdown }
  - &url {label: "URL", name: "href", widget: string}
  - &title_content_image [*title, *content, *image]
  - &sponsors
    - *title
    - {label: "Amount", name: amount, widget: string}
    - label: Sponsors
      name: sponsors
      widget: list
      fields:
        - *title
        - *image
        - *url
        - *content
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "index"
        file: "index.md"
        fields:
          - *title
          - *subtitle
          - *short_name
          - label: Actions
            name: actions
            widget: list
            fields:
              - label: "Destination"
                name: link_href
                widget: relation
                collection: pages
                displayFields: ["short_name"]
                searchFields: ["short_name"]
                valueField: permalink
              - {label: "Link Text", name: link_text, widget: string }
              - {label: "Blurb", name: content, widget: markdown }
              - *image
      - label: "About"
        name: "about"
        file: "about.md"
        fields:
          - *title
          - *subtitle
          - *short_name
          - label: Who We Are
            name: who_we_are
            widget: object
            fields: *title_content_image
          - label: Mission
            name: mission
            widget: object
            fields: [*title, *content]
          - label: History
            name: history
            widget: object
            fields: *title_content_image
          - label: Our Mentors
            name: our_mentors
            widget: object
            fields:
              - *title
              - *content
              - *image
              - label: Mentors
                name: mentors
                widget: list
                fields:
                  - {label: Name, name: name, widget: string }
                  - {label: Role, name: role, widget: string }

      - label: "Blog"
        name: "blog"
        file: "blog.md"
        fields:
          - *title
          - *subtitle
          - *short_name
      - label: "Shop"
        name: "shop"
        file: "shop.md"
        fields:
          - *title
          - *subtitle
          - *short_name
      - label: "Sponsors"
        name: "sponsors"
        file: "sponsors.md"
        fields:
          - *title
          - *subtitle
          - *short_name
          - label: Corporate
            name: corporate
            widget: object
            fields: *title_content_image
          - label: Great White
            name: great_white
            widget: object
            fields: *sponsors
          - label: Tiger Sharks
            name: tiger_sharks
            widget: object
            fields: *sponsors
          - label: Hammerhead Sharks
            name: hammerhead_sharks
            widget: object
            fields: *sponsors
          - label: Reef Sharks
            name: reef_sharks
            widget: object
            fields: *sponsors
          - label: Sponsor Us
            name: sponsor_us
            widget: object
            fields:
              - label: "Destination"
                name: link_href
                widget: relation
                collection: pages
                displayFields: ["short_name"]
                searchFields: ["short_name"]
                valueField: permalink
              - {label: "Link Text", name: link_text, widget: string }
              - {label: "Blurb", name: content, widget: markdown }

      - label: "Sponsor Us"
        name: "sponsor-us"
        file: "sponsor-us.md"
        fields:
          - *title
          - *subtitle
          - *short_name
          - {label: "Tagline", name: tagline, widget: string}
          - {label: "Intro", name: intro, widget: object, fields: [*title, *content]}
          - {label: "Become a Corporate Sponsor", name: become_a_corporate_sponsor, widget: object, fields: [*title, *content]}
          - {label: "Become a Personal Sponsor", name: become_a_personal_sponsor, widget: object, fields: [*title, *content]}
          - {label: "Sponsor Benefits", name: sponsor_benefits, widget: object, fields: [*title, *content]}
          - {label: "Need More Info?", name: need_more_info, widget: object, fields: [*title, *content]}
          - {label: "Donation Tiers", name: tiers_intro, widget: object, fields: [*title, *content]}
          - label: Tiers
            name: tiers
            widget: list
            fields:
              - *title
              - {label: "Amount", name: amount, widget: string}
              - *content

      - label: "Media"
        name: "media"
        file: "media.md"
        fields:
          - *title
          - *subtitle
          - *short_name
          - label: Social Media
            name: social_media
            widget: object
            fields:
              - *title
          - label: Photo Gallery
            name: photo_gallery
            widget: object
            fields:
              - *title
      - label: "Calendar"
        name: "calendar"
        file: "calendar.md"
        fields:
          - *title
          - *subtitle
          - *short_name
          - label: Intro
            name: intro
            widget: object
            fields:
              - *content
      - label: "Contact"
        name: "contact"
        file: "contact.md"
        fields:
          - *title
          - *subtitle
          - *short_name
          - {label: "Content", name: body, widget: markdown}

