---
---
{% if site.github.environment == "development" %}
{%comment%}For local development{%endcomment%}
# See https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
# for doing development locally.
backend:
  name: git-gateway
local_backend: true
{% else %}
backend:
  name: github
  repo: DeepBlueRoboticsMentors/DeepBlueRoboticsMentors.github.io
  branch: master
  site_domain: flamboyant-brattain-ce0789.netlify.com
{% endif %}

media_folder: "images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "index"
        file: "index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Name in navigation bar", name: short_name, widget: string}
          - label: Actions
            name: actions
            widget: list
            fields:
              - label: "Destination"
                name: link_href
                widget: relation
                collection: pages
                displayFields: ["short_name"]
                searchFields: ["short_name"]
                valueField: permalink
              - {label: "Link Text", name: link_text, widget: string }
              - {label: "Blurb", name: content, widget: markdown }
              - {label: "Image", name: image, widget: image }
      - label: "About"
        name: "about"
        file: "about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Name in navigation bar", name: short_name, widget: string}
      - label: "Blog"
        name: "blog"
        file: "blog.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Name in navigation bar", name: short_name, widget: string}
      - label: "Shop"
        name: "shop"
        file: "shop.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Name in navigation bar", name: short_name, widget: string}
      - label: "Sponsors"
        name: "sponsors"
        file: "sponsors.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Name in navigation bar", name: short_name, widget: string}
      - label: "Sponsor Us"
        name: "sponsor-us"
        file: "sponsor-us.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Name in navigation bar", name: short_name, widget: string}
      - label: "Media"
        name: "media"
        file: "media.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Name in navigation bar", name: short_name, widget: string}
      - label: "Calendar"
        name: "calendar"
        file: "calendar.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Name in navigation bar", name: short_name, widget: string}
      - label: "Contact"
        name: "contact"
        file: "contact.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Name in navigation bar", name: short_name, widget: string}
